version: '3'
services:
  nextjs-app:
    container_name: nextjs-app
    image: nguyenhuuchi3006/c-ecommerce-fe:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    # env_file: ../.env
    ports:
      - "3000:3000"
    # volumes:
      # - "/data/logs:/app/logs"
      # - "/data/public/uploads:/app/public/uploads"
    restart: no
